### ISSUE TITLE
Proje Konsepti HK.

### ISSUE THREAD

**Issue by VincentOfficial** [bekiroj/mtasa-roleplay-gamemode#1]
Merhabalar ,

Paket hakkında pek inceleme fırsatım olmadı fakat sql e baktığımda " Birlik " isimleri yabancı konsept fakat "SKİN" Textur kısımları TR konsepte uyarlı ? 

Paket konsepti nedir acaba?

Saygılarımla iyi çalışmalar :)

**Comment by bekiroj** [comment]
TR konseptine göre ayarlanıyorken sonradan yabancı konseptine geçiş yapmaya karar verdik, skin ve kaplama kısımlarını değiştirerek yabancı konseptinde, veya tam tersini yaparak TR konseptinde kullanabilirsiniz

**Comment by VincentOfficial** [comment]
Teşekkür ederim , Sanırım OOP bir paket ve DBConnect ufak bir inceledim.
(Redmancey veya Hypnos değil ? )
